name: Test suite

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:

jobs:
  tests:
    name: Meteor package tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - meteor-version: 2.10
            node-version: 14
          - meteor-version: 3.1.2
            node-version: 22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Meteor ${{ matrix.meteor-version }}
        uses: meteorengineer/setup-meteor@v2
        with:
          meteor-release: ${{ matrix.meteor-version }}

      - name: Install and test
        run: |
          meteor npm install
          meteor npm run test:once
